config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:show]
  resources :products do
    resources :ratings, only: [:new, :create]
  end
  resources :ratings, only: [:index, :destroy]
end

app/views/shared/_card.html.erb
<div class="card-deck mt-4">
  <% @products.each do |product| %>
  <div class="card">
    <% if product.photos.attached? %>
      <%= cl_image_tag product.photos.first.key %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= product.name %></h5>
      <p class="card-text"><%= product.admin_rating %> stars</p>
      <p class="card-text"><small class="text-muted"><%= link_to 'More details', product_path(product) %></small></p>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="form">
  <%= simple_form_for(product) do |f| %>
    <%= f.input :name %>
    <%= f.input :admin_rating, input_html: { min: '0', max: '5' }%>
    <%= f.input :release_date, label: "Release date (example: 'September 2020')" %>
    <%= f.input :description %>
    <%= f.input :snippet %>
    <%= f.input :design %>
    <%= f.input :autonomy %>
    <%= f.input :performance %>
    <%= f.input :advantages %>
    <%= f.input :disadvantages %>
    <%= f.association :category, collection: Category.all %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</div>
<div class="back-btn mt-2">
  <%= link_to '< Back to Home', root_path, class: 'btn btn-primary' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
  <div id='nav-logo' class='navbar-brand'>
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', id: 'logo-img' %>
    <% end %>
  </div>

  <div class="menu">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <%= image_tag "star.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">            
            <% if user_signed_in? %>
              <%= link_to "My reviews", ratings_path, class: "dropdown-item" %>
              <%= link_to 'Settings', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'dropdown-item'  %>
              <%= link_to "Login", new_user_session_path, class: 'dropdown-item'  %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div id='nav-menu' class="navbar-light navbar-lewagon">
  <ul>
    <div id='categories' class="row d-flex">
      <% Category.all.each do |category| %>
        <%= link_to category_path(category) do %>
          <li class="category"><%= category.name %></li>
        <% end %>
      <% end %>
    </ul>  
  </div>
</div>