config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:show]
  resources :products do
    resources :ratings, only: [:new, :create]
  end
  resources :ratings, only: [:index, :destroy]
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = policy_scope(Rating)
  end
  
  def new
    @product = Product.find(params[:product_id])
    @rating = Rating.new
  end
  
  def create
    @rating = Rating.new(rating_params)
    @rating.product = Product.find(params[:product_id])
    @rating.user = current_user
    if @rating.save
      redirect_to product_path(@rating.product)
    else
      render :new
    end
  end
  
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy
    redirect_to ratings_path 
    # authorize @rating
  end
  
  private
  
  def rating_params
    params.require(:rating).permit(:comment, :rating)
  end
end

app/views/ratings/index.html.erb
<h1>Your reviews</h1>

<ul>
  <% @ratings.each do |rating| %>
    <li>
      <%= rating.rating %>
      <%= rating.comment %>
      <%= link_to 'Remove', rating_path(rating), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

app/views/ratings/new.html.erb
<div class="form">
  <%= simple_form_for [@product, @rating] do |f| %>
    <%= f.input :rating, input_html: { min: '0', max: '5' } %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>
<div class="back-btn mt-2">
  <%= link_to '< Cancel', product_path(@product), class: 'btn btn-primary' %>
</div>