config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :categories, only: [:show]
  resources :products do
    resources :ratings, only: [:new, :create]
  end
  resources :ratings, only: [:index, :destroy]
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :ratings, dependent: :destroy
  belongs_to :category
  has_many_attached :photos
  
  validates :admin_rating, numericality: {less_than_or_equal_to: 5}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_products, only: [:show, :edit, :update, :destroy]
  
  def index
    @products = policy_scope(Product)
  end
  
  def show
    @ratings = @product.ratings
  end
  
  def new
    @product = Product.new
    authorize @product
  end
  
  def create
    @product = Product.new(product_params)
    authorize @product
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    @product.update(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :edit
    end
  end
  
  def destroy
    @product.destroy
    redirect_to products_path
  end
  
  private
  
  def product_params
    params.require(:product).permit(:admin_rating, :name, :release_date, :description, :snippet, :design, :autonomy, :performance, :advantages, :disadvantages, :category_id, photos: [])
  end
  
  def set_products
    @product = Product.find(params[:id])
    authorize @product
  end
end

app/views/products/edit.html.erb
<%= render './shared/form', product: @product %>

app/views/products/index.html.erb
<h1>All products</h1>

<div class="home-btn d-flex justify-content-center mb-4">
  <%= link_to 'Add a product', new_product_path, class: 'btn btn-primary' %>
</div>

<%= render './shared/card' %>

app/views/products/new.html.erb
<%= render './shared/form', product: @product %>

app/views/products/show.html.erb
<div class="row d-grid">
  <div id="product-title">
    <h1><%= @product.name %></h1>
    <h4><%= @product.snippet %></h4>
  </div>
  <div id="product-img">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @product.photos.each do |photo| %>
        <div class="carousel-item active">
          <%= cl_image_tag photo.key, class: 'd-block w-50' %>
        </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div id="product-content">
    <p><%= @product.description %></p>
    <p><%= @product.design %></p>
    <p><%= @product.performance %></p>
    <p><%= @product.autonomy %></p>
  </div>
</div>
<div class="row d-flex justify-content-between mt-3">
  <div class="advantages w-50">
    <h3>Points forts</h3>
    <p><%= @product.advantages %></p>
  </div>
  <div class="disadvantages w-50">
    <h3>Points faibles</h3>
    <p><%= @product.disadvantages %></p>
  </div>
</div>

<div class="row mt-3">
  <h4>Reviews</h4>
</div>
<div class="row mt-3"">
  <div class="rating-user d-grid">
    <% @ratings.each do |rating| %>
      <p><%= rating.user.username %></p>
      <p><%= rating.rating %> stars</p>
      <p><%= rating.comment %></p>
    <% end %>
  </div>
</div>

<%= link_to 'Leave a review', new_product_rating_path(@product) %>

<div class="product-btn">
  <div class="product-edit mt-2">
    <%= link_to 'Edit product', edit_product_path(@product), class: 'btn btn-warning'%>
  </div>
  <div class="product-destroy mt-2">
    <%= link_to 'Remove product', product_path(@product), method: :delete, class: 'btn btn-danger'%>
  </div>
  <div class="back-btn mt-2">
    <%= link_to '< Back to Home', root_path, class: 'btn btn-primary' %>
  </div>
</div>